In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [3]:
df= pd.read_csv('Bank-data.csv')
df.head()

Index  interest_rate  credit  Gender  previous  duration Churn
0      0          1.334       0       1         0       117    no
1      1          0.767       0       0         1       274   yes
2      2          4.858       0       1         0       167    no
3      3          4.120       0       0         0       686   yes
4      4          4.856       0       1         0       159    no

In [10]:
df.shape

(518, 7)

In [4]:
df['Churn'].value_counts()

no     259
yes    259
Name: Churn, dtype: int64

In [5]:
df['Churn']= df['Churn'].astype('category')
df['Churn']= df['Churn'].cat.codes
df.head()

Index  interest_rate  credit  Gender  previous  duration  Churn
0      0          1.334       0       1         0       117      0
1      1          0.767       0       0         1       274      1
2      2          4.858       0       1         0       167      0
3      3          4.120       0       0         0       686      1
4      4          4.856       0       1         0       159      0

In [6]:
x= df.iloc[:, 0:-1].values
y= df.iloc[:,-1].values
df.head()

Index  interest_rate  credit  Gender  previous  duration  Churn
0      0          1.334       0       1         0       117      0
1      1          0.767       0       0         1       274      1
2      2          4.858       0       1         0       167      0
3      3          4.120       0       0         0       686      1
4      4          4.856       0       1         0       159      0

In [7]:
# Split the data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, random_state=1)

## Logistic regression

In [8]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [9]:
y_pred_train_lr= lr.predict(x_train)
y_pred_test_lr= lr.predict(x_test)

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(classification_report(y_train, y_pred_train_lr))
print('..........................................')
print(classification_report(y_test, y_pred_test_lr))
print('..........................................')
print(confusion_matrix(y_train, y_pred_train_lr))
print('..........................................')
print(confusion_matrix(y_test, y_pred_test_lr))
print('..........................................')
print(accuracy_score(y_train, y_pred_train_lr))
print('..........................................')
print(accuracy_score(y_test, y_pred_test_lr))

              precision    recall  f1-score   support

           0       0.87      0.82      0.85       190
           1       0.84      0.88      0.86       198

    accuracy                           0.85       388
   macro avg       0.85      0.85      0.85       388
weighted avg       0.85      0.85      0.85       388

..........................................
              precision    recall  f1-score   support

           0       0.86      0.94      0.90        69
           1       0.93      0.82      0.87        61

    accuracy                           0.88       130
   macro avg       0.89      0.88      0.88       130
weighted avg       0.89      0.88      0.88       130

..........................................
[[156  34]
 [ 23 175]]
..........................................
[[65  4]
 [11 50]]
..........................................
0.8530927835051546
..........................................
0.8846153846153846


## PCA

In [11]:
from sklearn.decomposition import PCA

In [12]:
pca= PCA(n_components= None) # None- means all variables
x_train_n= pca.fit_transform(x_train)
x_test_n= pca.fit_transform(x_test)

In [13]:
x_train_n

array([[-1.33275216e+02,  2.18199956e+02,  1.43073708e+00,
        -1.83874638e-01, -1.13060767e-01, -1.43648454e-02],
       [-2.29738719e+02,  5.82374107e+01,  2.17316712e+00,
        -2.17112061e-01, -3.61840218e-02, -1.48696346e-02],
       [ 1.79042546e+01,  1.31930421e+02, -1.82838072e+00,
        -2.08725841e-01, -3.24426421e-01, -7.93385332e-02],
       ...,
       [-8.28937221e+01, -1.82977248e+02,  1.99770301e+00,
        -2.75841563e-01, -6.43555733e-03, -3.61118661e-02],
       [ 7.57419483e+02, -3.80172779e+01, -1.87359640e+00,
        -2.67849745e-01, -2.88487227e-01, -8.59009154e-02],
       [-3.13593313e+02, -2.13020681e+02,  1.06417537e+00,
        -2.76509946e-01, -7.01893763e-02, -5.81594008e-02]])

In [14]:
pd.DataFrame(x_train_n)

0           1         2         3         4         5
0   -133.275216  218.199956  1.430737 -0.183875 -0.113061 -0.014365
1   -229.738719   58.237411  2.173167 -0.217112 -0.036184 -0.014870
2     17.904255  131.930421 -1.828381 -0.208726 -0.324426 -0.079339
3    -94.358638  260.375079 -1.719726 -0.176496 -0.339712 -0.068122
4   -293.187143   -8.413217  2.001713  0.759624  0.083901  0.045998
..          ...         ...       ...       ...       ...       ...
383 -126.656730 -125.019591 -1.507354 -0.262703 -0.261719 -0.095975
384  257.576721 -118.286614  1.971776  0.719370  0.108172  0.042539
385  -82.893722 -182.977248  1.997703 -0.275842 -0.006436 -0.036112
386  757.419483  -38.017278 -1.873596 -0.267850 -0.288487 -0.085901
387 -313.593313 -213.020681  1.064175 -0.276510 -0.070189 -0.058159

[388 rows x 6 columns]

In [15]:
pd.DataFrame(x)

0      1    2    3    4      5
0      0.0  1.334  0.0  1.0  0.0  117.0
1      1.0  0.767  0.0  0.0  1.0  274.0
2      2.0  4.858  0.0  1.0  0.0  167.0
3      3.0  4.120  0.0  0.0  0.0  686.0
4      4.0  4.856  0.0  1.0  0.0  159.0
..     ...    ...  ...  ...  ...    ...
513  513.0  1.334  0.0  1.0  0.0  204.0
514  514.0  0.861  0.0  0.0  1.0  806.0
515  515.0  0.879  0.0  0.0  0.0  290.0
516  516.0  0.877  0.0  0.0  1.0  473.0
517  517.0  4.965  0.0  0.0  0.0  142.0

[518 rows x 6 columns]

In [17]:
explained_variance= pca.explained_variance_ratio_

In [18]:
explained_variance

array([8.21090925e-01, 1.78877574e-01, 2.90760395e-05, 1.74063800e-06,
       5.33010532e-07, 1.50409984e-07])

###### Significance of 1st and 2nd column
- 1st column= 0.821
- 2nd column= 0.178

In [19]:
# n_components= 2
pca= PCA(n_components= 2) # None- means all variables
x_train_2= pca.fit_transform(x_train)
x_test_2= pca.fit_transform(x_test)

In [20]:
pd.DataFrame(x_train_2)

0           1
0   -133.275216  218.199956
1   -229.738719   58.237411
2     17.904255  131.930421
3    -94.358638  260.375079
4   -293.187143   -8.413217
..          ...         ...
383 -126.656730 -125.019591
384  257.576721 -118.286614
385  -82.893722 -182.977248
386  757.419483  -38.017278
387 -313.593313 -213.020681

[388 rows x 2 columns]

## Logistic Regression PCA

In [21]:
lr_pca= LogisticRegression()
lr_pca.fit(x_train_2, y_train)

LogisticRegression()

In [22]:
y_pred_train_lr_pca= lr_pca.predict(x_train_2)
y_pred_test_lr_pca= lr_pca.predict(x_test_2)

In [23]:
print(classification_report(y_train, y_pred_train_lr_pca))
print('..........................................')
print(classification_report(y_test, y_pred_test_lr_pca))
print('..........................................')
print(confusion_matrix(y_train, y_pred_train_lr_pca))
print('..........................................')
print(confusion_matrix(y_test, y_pred_test_lr_pca))
print('..........................................')
print(accuracy_score(y_train, y_pred_train_lr_pca))
print('..........................................')
print(accuracy_score(y_test, y_pred_test_lr_pca))

              precision    recall  f1-score   support

           0       0.64      0.76      0.69       190
           1       0.72      0.59      0.65       198

    accuracy                           0.67       388
   macro avg       0.68      0.67      0.67       388
weighted avg       0.68      0.67      0.67       388

..........................................
              precision    recall  f1-score   support

           0       0.72      0.83      0.77        69
           1       0.76      0.64      0.70        61

    accuracy                           0.74       130
   macro avg       0.74      0.73      0.73       130
weighted avg       0.74      0.74      0.74       130

..........................................
[[144  46]
 [ 81 117]]
..........................................
[[57 12]
 [22 39]]
..........................................
0.6726804123711341
..........................................
0.7384615384615385


## Cross validation

In [26]:
from sklearn.model_selection import cross_val_score
training_accuracy= cross_val_score(lr_pca, x_train_2, y_train, cv=10)
test_accuracy= cross_val_score(lr_pca, x_test_2, y_test, cv=10)
print(training_accuracy.mean())
print('..................')
print(test_accuracy.mean())

0.6724696356275304
..................
0.7846153846153846
